# Generated by Django 5.0.3 on 2024-05-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_address_remove_student_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_name', models.CharField(max_length=64)),
                ('date_issued', models.DateField()),
                ('certificate_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
